### ISSUE TITLE
Update `path` dependency constraints to ^1.9.0

### ISSUE THREAD

**Issue by therohansanap** [dsc-uob/subtitle#14]
Getting conflict with `flutter_test` dependency hence need to update this constraint. I tried to do it myself and raise a PR but I do not have permission to push the branch.

**Comment by therohansanap** [comment]
PR raised - https://github.com/dsc-uob/subtitle/pull/15

**Comment by Bolling88** [comment]
Plus one on this, please approve this dudes pr :)
