### ISSUE TITLE
Srt subtitles parsing don't work

### ISSUE THREAD

**Issue by ofceab** [dsc-uob/subtitle#2]
I tried to use that package for parsing an srt file but don't work.
I deeped into the code and noticed the RegEx use for VTT files is the same used for SRT file. I think then that where the issue come from it.

**Comment by MuhmdHsn313** [comment]
Hello @ofceab 
In fact, there is a lot of similarity between VTT and SRT, so I used the same regex for both. Please provide the string you try to decode with this package for the purpose of solving the problem.
Thanks.

**Comment by ofceab** [comment]
Hello @MuhmdHsn313 
Let me provide you that

`1
00:00:02,347 --> 00:00:07,951
A l’Ouest le soleil se couche

2
00:00:08,917 --> 00:00:13,487
Il arrive à la fin de sa course

3
00:00:14,411 --> 00:00:18,748
Et je vois combien ce temps est là

4
00:00:19,367 --> 00:00:23,891
Oh le temps du coucher du soleil

5
00:00:25,434 --> 00:00:27,331
C’est la fin

6
00:00:28,206 --> 00:00:29,885
C’est la fin

7
00:00:31,158 --> 00:00:34,972
C’est la fin de la course

8
00:00:35,712 --> 00:00:37,638
C’est la fin

9
00:00:38,212 --> 00:00:40,106
C’est la fin

10
00:00:40,965 --> 00:00:44,810
C’est la fin de toute chose

11
00:00:46,198 --> 00:00:50,374
Et voici que la lumière du soir

12
00:00:51,015 --> 00:00:54,854
A l’Ouest pour moi a paru

13
00:00:55,649 --> 00:00:59,895
Elle manifeste le fils de l’homme

14
00:01:00,301 --> 00:01:03,707
Et je crois c’est vrai je crois

15
00:01:03,775 --> 00:01:04,775

`

I tried to have String in variable some worked fine, but when I tried to load from assets it doesn't work, I tried and retried nothing

**Comment by MuhmdHsn313** [comment]
Solved!
