### ISSUE TITLE
Using URL Notworking

### ISSUE THREAD

**Issue by PhuCG** [dsc-uob/subtitle#5]
var url = Uri.parse(
      'https://brenopolanski.github.io/html5-video-webvtt-example/MIB2-subtitles-pt-BR.vtt');
  var controller = SubtitleController(
    provider: NetworkSubtitle(
      url,
      type: SubtitleType.vtt,
    ),
  );

I cant get subtitles in this link??? how fix that ! plse help

**Comment by PhuCG** [comment]
I found the problem!
The problem is in the path, I'm not sure because of the way to convert the path when concatenating by "-" characters
When I created a path for myself it worked.

before: https://brenopolanski.github.io/html5-video-webvtt-example/MIB2-subtitles-pt-BR.vtt
after: https://docdn.giainhanh.io/media/listening/test/test_en.vtt
I work !

**Comment by PhuCG** [comment]
I found the problem!
The problem is in the path, I'm not sure because of the way to convert the path when concatenating by "-" characters
When I created a path for myself it worked.

Before: https://brenopolanski.github.io/html5-video-webvtt-example/MIB2-subtitles-pt-BR.vtt
After:
My URL: https://docdn.giainhanh.io/media/listening/test/test_en.vtt
Its work !

**Comment by MuhmdHsn313** [comment]
Dear @PhuCoderrga 
Could you create a pull request for it?

**Comment by MuhmdHsn313** [comment]
Solved in #8
